// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djhekdeamydqdupnfuvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqaGVrZGVhbXlkcWR1cG5mdXZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0NjUyNDUsImV4cCI6MjA5MTA0MTI0NX0.QzKEiebsJV-fUseF710h-fBqmWWnjZb3cJuNOf4SmnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});